"""Convert analysis JSON to a Markdown report."""

from typing import Any


def generate_report(
    owner: str,
    repo: str,
    analysis: dict[str, Any],
    n_merged: int,
    n_rejected: int,
    generated_date: str,
) -> str:
    """Return a complete Markdown report string."""
    lines: list[str] = []

    def h(text: str):
        lines.append(text)

    def sep():
        lines.append("\n---\n")

    # Header
    h(f"# Contribution Intelligence Report")
    h(f"")
    h(f"**Repository:** {owner}/{repo}")
    h(f"**Generated:** {generated_date}")
    h(f"**Based on:** {n_merged} merged PRs · {n_rejected} rejected PRs")
    sep()

    # TL;DR
    h("## TL;DR")
    h("")
    h(analysis.get("summary", "_No summary available._"))
    sep()

    # PR Size Sweet Spot
    sweet_spot = analysis.get("pr_size_sweet_spot", {})
    h("## PR Size Sweet Spot")
    h("")
    h(sweet_spot.get("insight", "_No data._"))
    h("")
    h(f"**Recommendation:** {sweet_spot.get('recommendation', '_No data._')}")
    sep()

    # Why PRs Get Rejected
    h("## Why PRs Get Rejected")
    h("")
    rejection_patterns = analysis.get("rejection_patterns", [])
    if rejection_patterns:
        for rp in rejection_patterns:
            pattern = rp.get("pattern", "Unknown pattern")
            quote = rp.get("example_quote", "")
            avoid = rp.get("how_to_avoid", "")
            h(f"### ❌ {pattern}")
            h("")
            if quote:
                h(f'> "{quote}"')
                h("")
            h(f"**How to avoid it:** {avoid}")
            h("")
    else:
        h("_Not enough data to identify rejection patterns._")
        h("")
    sep()

    # Implicit Style Rules
    h("## Implicit Style Rules")
    h("")
    style_rules = analysis.get("implicit_style_rules", [])
    if style_rules:
        for sr in style_rules:
            rule = sr.get("rule", "")
            evidence = sr.get("evidence", "")
            h(f"- **{rule}** — *{evidence}*")
    else:
        h("_No implicit style rules detected._")
    sep()

    # Maintainer Patterns
    h("## Maintainer Patterns")
    h("")
    mp = analysis.get("maintainer_patterns", {})
    response_time = mp.get("response_time", "_Unknown_")
    key_reviewers = mp.get("key_reviewers", "_Unknown_")
    other = mp.get("other", "")
    h(f"- **Response time:** {response_time}")
    h(f"- **Key reviewers:** {key_reviewers}")
    if other:
        h(f"- {other}")
    sep()

    # First PR Checklist
    h("## ✅ Your First PR Checklist")
    h("")
    checklist = analysis.get("first_pr_checklist", [])
    if checklist:
        for item in checklist:
            h(f"- [ ] {item}")
    else:
        h("_No checklist items generated._")
    h("")
    sep()

    h("*Generated by contrib-intel*")

    return "\n".join(lines)
